name: AdventCalendar
version: '${project.version}'
main: net.pullolo.adventcalendar.AdventCalendar
api-version: '1.20'
commands:
  gui:
    description: Show guis
    usage: /<command> <gui>
    permission: ac.gui
